### ISSUE TITLE
Laravel sanctum 404 not found at /api

### ISSUE THREAD

**Issue by keedle** [nevadskiy/laravel-nuxt-docker#10]
Hello,
When I try to make get request in postman to _localhost:8080/api/sanctum/csrf-cookie_ I'm always getting 404 not found, however, if I change the port to 8081 and remove/api bit it works and gives me 204. Any ideas why that happens ?
Thank you.

**Comment by xalaida** [comment]
Hello, @keedle.
All requests without `/api` prefix are proxied to the nuxt instance, that's why you can't hit sanctum endpoint.

By default, sanctum package uses `/sanctum` prefix as default. 
You need to replace that prefix it in the `api/config/sanctum.php` like this:
```
'prefix' => 'api/sanctum'
```
Thanks.

**Comment by xalaida** [comment]
Note, that you need to prefix all your Laravel routes with `api` to make them available from the nuxt app, not only sanctum's.

**Comment by keedle** [comment]
Thank you for help, kinda missed prefix bit in sanctum's docs. 
Thank you for such a great docker build.

**Comment by jishnukb2022** [comment]
Hello 
How to fix this issue ? I can't fix  -> http://localhost:3000/sanctum/csrf-cookie 404 (Not Found)  
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:66:1)

**Comment by s17-git** [comment]
Same problem here

**Comment by hassan1165** [comment]
same problem here

**Comment by sharpprahs** [comment]
same problem, when i use prefix my application routes middleware not working
