### ISSUE TITLE
Error while trying to require a new composer package

### ISSUE THREAD

**Issue by Kaasfonthijn** [nevadskiy/laravel-nuxt-docker#11]
Hi @nevadskiy,

First of al thank you for the build, it's great! 

I ran into a problem while adding a composer package. I got the message: Your requirements could not be resolved to an installable set of packages. 

![image](https://user-images.githubusercontent.com/33329554/81300950-b24baa80-9078-11ea-8c4b-34dd352f1791.png)

So i checked the php ini file and noticed that there a couple of extensions where missing (compare image below to the first one)

![image](https://user-images.githubusercontent.com/33329554/81301305-2c7c2f00-9079-11ea-9a8f-db3174c43f33.png)

I checked the php dockerfile in the project (docker/dev/php/DockerFile) and noticed that the install for  bcmath was there, but somehow it was not present in the php.ini file

![image](https://user-images.githubusercontent.com/33329554/81301675-a44a5980-9079-11ea-9cf9-1d9c872e3003.png)

Is the problem caused because it's missing, and how do i fix it? or does it have to do with something else?

Thanks in advance!

**Comment by xalaida** [comment]
Hi @Kaasfonthijn. Give me few minutes, I'll check it.

**Comment by xalaida** [comment]
Could you please also tell me your OS?

**Comment by Kaasfonthijn** [comment]
Thanks for the quick reply!
I noticed that the bcmath wasn´t missing. It was: docker-php-ext-zip.ini. I tried adding that one, but that still didn't fix it.

My OS is Windows 10 Pro

**Comment by xalaida** [comment]
Seems like for this particular package you need to add a sockets extension.

You can install it easly just adding a new line in the `docker/dev/php/Dockerfile`
There are good place just below the redis extension section
```
# Sockets
RUN docker-php-ext-install sockets
```

Also rebuild the php container with `docker-compose build php` command.

Then try to install the `nesk/puphpeteer` package again.

Also note, if you are going to use this extension in the queue, you also need to add this line to the `docker/dev/supervisor/Dockerfile` file in the same way.

Thanks a lot and good luck.

**Comment by Kaasfonthijn** [comment]
I followed the steps without any errors, but somehow i still got the same error message while trying to install ``nesk/puphpeteer`` .

![image](https://user-images.githubusercontent.com/33329554/81306905-51c06b80-9080-11ea-9d33-f745cf768360.png)

![image](https://user-images.githubusercontent.com/33329554/81306451-c941cb00-907f-11ea-806f-3da7f7588f4c.png)

**Comment by xalaida** [comment]
Looks weird. I have installed the package without any problem.
The error message is only about the missing sockets extension.

First at all, try to simple restart everything and reinstall the package again.

If it does not help, try to build the container with no cache following these steps:
```
docker-compose build php --no-cache
docker-compose restart
docker-compose exec php composer require nesk/puphpeteer
```

**Comment by Kaasfonthijn** [comment]
It worked! Cache was the issue i guess, and the lack of knowledge. 😅
 
You are a legend, thanks for helping!
