### ISSUE TITLE
Feature production build

### ISSUE THREAD

**Issue by rivassh** [nevadskiy/laravel-nuxt-docker#12]
If I want to use your docker-compose on production what is your recommendations?

**Comment by xalaida** [comment]
No, currently there is only dev build.
Hope, I will add prod build in the nearest future.
You can create your own `docker-compose.prod.yml` file and `/docker/prod/` directory with configuration for your needs.
Or just look for another prod-ready builds.
Thanks.

**Comment by peymanforceman** [comment]
Hi @nevadskiy , thanks for the amazing docker configuration but I have the same request as @hmdshariati has. 

can you add a production-ready build for this boilerplate ?

**Comment by xalaida** [comment]
Hi @peymanforceman.
I would do, but there are few limits depending on server you are going to use, CI / DI stuff, and others.
I personally use private docker hub repo for my apps and I dont think this is a good approach for everyone.
I'll try to find a way to make a free, simple and good build which does not depend on specific services and environments, but I need some time and probably help for this. 
Would be nice if we could cooperate and make it together.

**Comment by DenisBorisenko** [comment]
@nevadskiy hey :)

thanks for a very cool repository.

I would like to understand what is the difficulty in configuring for production?
I would gladly help.

my telegram @ vitoSkalete72

**Comment by xalaida** [comment]
Hi @DenisBorisenko!
Currently lack of time is the main issue.

**Comment by HassanYA** [comment]
It would be beautiful to have production build

**Comment by DenisBorisenko** [comment]
> Hi @DenisBorisenko!
> Currently lack of time is the main issue.

I am now finishing setting up app for deploy on AWS which use your configuration.
When I'm done with that, I can create a Pull Request with my production setup.
what do you think about it? 

aws services: CodePipelines(CodeCommit + CodeBuild) + ElasticBeanstalk

**Comment by xalaida** [comment]
@DenisBorisenko That sounds awesome.

**Comment by xalaida** [comment]
Finally done #41
