### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by rivassh** [nevadskiy/laravel-nuxt-docker#13]
http://deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
`Reading package lists...
W: GPG error: http://deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
W: GPG error: http://security.debian.org/debian-security buster/updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security buster/updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian buster-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.
ERROR: Service 'supervisor' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
make: *** [Makefile:43: build] Error 1
`

**Comment by xalaida** [comment]
Hi @hmdshariati.
Try to use
```
docker-compose build --no-cache
```
