### ISSUE TITLE
504 Gateway Timeout Nuxtjs

### ISSUE THREAD

**Issue by ederson-cinnamon** [nevadskiy/laravel-nuxt-docker#15]
Hi @nevadskiy ,

This repo is really helpful.
I wanted to dockerized our existing Laravel and Nuxtjs file.

Do I have to change any config on .env for the client because I'm getting 504 Gateway Timeout.

If you have any insight into what I'm missing please let me know.

Thank you.

**Comment by xalaida** [comment]
Hi @ederson-cinnamon.

On the client side you need to do:

- Install dotenv module: https://github.com/nuxt-community/dotenv-module

- Add the following line at the very top of the `nuxt.config.js`
```
require('dotenv').config()
```
- Register it in the modules list in the `nuxt.config.js`

See: https://github.com/nevadskiy/laravel-nuxt-docker/blob/master/client/nuxt.config.js

Finally copy `/.env.client` into `client/.env` and restart `client` docker container
