### ISSUE TITLE
SSL certificate, nginx config

### ISSUE THREAD

**Issue by Icon003** [nevadskiy/laravel-nuxt-docker#17]
Hello, I would like to configure nginx to work with https, but when I connect an ssl certificate to your config, I get (400 bad request the plain http request was sent to https port) Apparently due to the fact that ajax requests go to http, please tell me how I can fix the situation. Thank you in advance!

**Comment by xalaida** [comment]
Hello @Icon003.
I don't use SSL config for dev, so I cannot help.

**Comment by xalaida** [comment]
If you set up nginx configuration for the prod envoronment, make sure you are using 443 port and https schema.
