### ISSUE TITLE
Change the install directory for composer.

### ISSUE THREAD

**Issue by tcampbPPU** [nevadskiy/laravel-nuxt-docker#23]
First thing this is really great! I've been looking forever for a Laravel and Nuxt Docker network and this is what I hoped for!

I did run into issue when running the `make install` command, inside of `docker/dev/php/Dockerfile` the 
```
RUN chmod 0755 /usr/bin/composer
```
failed and error was that path to composer couldn't be found. I changed these 2 lines then it was working for me
```
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin/ --filename=composer
RUN chmod 0755 /usr/local/bin/composer
```

**Comment by xalaida** [comment]
Hi @tcampbPPU. Thanks for the issue. I really have no clue why that happened.

**Comment by xalaida** [comment]
Yes, probably there is an issue on some environments.
I'm going to update the composer installation command with this
```
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
```
That should work fine

**Comment by tcampbPPU** [comment]
Sounds good, Thanks!

**Comment by tcampbPPU** [comment]
I testing on Ubuntu 20.10 everything is working great!

**Comment by xalaida** [comment]
Fine, thank you.
