### ISSUE TITLE
ERROR: Service 'php' failed to build : Build failed

### ISSUE THREAD

**Issue by Rasool-deldar** [nevadskiy/laravel-nuxt-docker#25]
Please fix this problem when make install programs that are installed last.

=> ERROR [stage-0  6/24] RUN apt-get install -y libzip-dev zip && docker-php-ext-configure zip && docker-php-ext  0.9s
------
 > [stage-0  6/24] RUN apt-get install -y libzip-dev zip && docker-php-ext-configure zip && docker-php-ext-install zip:
#9 0.795 Reading package lists...
#9 0.814 Building dependency tree...
#9 0.815 Reading state information...
#9 0.818 E: Unable to locate package libzip-dev
#9 0.818 E: Unable to locate package zip
------
executor failed running [/bin/sh -c apt-get install -y libzip-dev zip && docker-php-ext-configure zip && docker-php-ext-install zip]: exit code: 100
ERROR: Service 'php' failed to build : Build failed
make: *** [Makefile:7: up] Error 1

**Comment by xalaida** [comment]
@Rasool-deldar try to run the build command with the `--no-cache` option.

```
make build-no-cache
```
