### ISSUE TITLE
Can't access to $fetchState

### ISSUE THREAD

**Issue by LynxTR** [nevadskiy/laravel-nuxt-docker#30]
Only $fetchState.error accessible at async fetch(){}

Simplest example is: 

```
<script>
  export default {
    data: () => ({
      data: null,
    }),
  
    async fetch() {
      this.data = await this.$axios.$get('/api/v1/categories')
    },
  }
</script>

<template>
  <main>
    <content-placeholders
      v-if="$fetchState.pending || $fetchState.error"
    >
     <content-placeholders-img />
    </content-placeholders>
    <!--  -->
    <!--  -->
    <!--  -->
    <pre v-else>
      {{ data }}
    </pre>
  </main>
</template>
```

Is there anyway to fix this problem? Cause async fetch provides a lot of help by managing component level fetches and seems like it's status response is undefined:

![Ekran görüntüsü 2021-08-05 210652](https://user-images.githubusercontent.com/64704879/128400312-28b93a94-0b34-4f0c-9120-65187df99ab8.png)

If it's not possible to fix this problem, is there a way to pull off nginx proxy /api- that way, i can work around with @nuxt/proxy and reach to laravel.

**Comment by xalaida** [comment]
@LynxTR I use $fetch a lot and did not face this problem at all. I do not think it is related to the docker.

Does the API call work if you put it into the mounted() hook?
