### ISSUE TITLE
 error Couldn't find a package.json file in "/var/www/client"

### ISSUE THREAD

**Issue by ibalaji777** [nevadskiy/laravel-nuxt-docker#31]
wheni run docker-compose up,getting this error
 error Couldn't find a package.json file in "/var/www/client"

**Comment by xalaida** [comment]
Hi, @ibalaji777! You must install Nuxt first. Use `make install` command.

**Comment by milosb793** [comment]
@nevadskiy  When using `make install`, still getting `#9 0.293 /bin/sh: nuxt: not found`

**Comment by xalaida** [comment]
Try `./install.sh` command. Should work fine.
