### ISSUE TITLE
Build errors on running `make install`

### ISSUE THREAD

**Issue by connecteev** [nevadskiy/laravel-nuxt-docker#32]
I am new to Docker and was looking to get up to speed with a barebones laravel+nuxt+docker skeleton app. Your repo looked like a good starting point, so I freshly installed docker for desktop on my Mac. Unfortunately the build errors out, see below.

## Error # 1:

I ran the command ```make install```:

The build for ```install-laravel``` continues up to this point, and errors out:
``` 
sudo chown ${USER}:${USER} -R api
Password:
chown: kp123: illegal group name
```
Note: (my Mac has no group named kp123, which is the user I am logged in as:)
$ whoami
kp123

I commented out both of these lines in Makefile 
```
# sudo chown ${USER}:${USER} -R api

# sudo chown ${USER}:${USER} -R client
```

and proceeded to re-rerun ```make install```, before seeing error # 2.
Note: it would be good to not have the script stop and ask for a password, if that can be helped.

## Error # 2:
The build for ```install-laravel``` finishes, then then build for ```install-nuxt``` starts and continues up to this point, and errors out:
``` 
cp .env.client client/.env
sed -i "1i require('dotenv').config()" client/nuxt.config.js
sed: 1: "client/nuxt.config.js": command c expects \ followed by text
make: *** [install-nuxt] Error 1
```
Note: it would be good to not have the script stop and ask for all the nuxt settings (project name, framework, PWA settings, etc) and specify them somewhere they can be configured (.env, nuxt.config.js, etc?)

**Comment by xalaida** [comment]
Hi @connecteev.
Error 1: Yes, it was a permission issue. Fixed now.
Error 2: Nuxt asks about specific tools that developers can prefer so it is good to have an option to select preferred ones.

**Comment by connecteev** [comment]
Thank you @nevadskiy I will give this another try
