### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by afrizal423** [nevadskiy/laravel-nuxt-docker#35]
Hello, I have a question.
how to make a schematic like this image ? ![alt text](https://raw.githubusercontent.com/nevadskiy/laravel-nuxt-docker/master/docker/schema.png)

I thank you for this template, it really helped me in completing my undergraduate thesis project.
But I need to draw a new schematic, maybe not much different from the schema you created.
what is the name of the software/link to create the schematic?

**Comment by xalaida** [comment]
@afrizal423 hi, thank you!

I use this: https://app.diagrams.net/

**Comment by afrizal423** [comment]
Oh I see.
ok thank you 👌
