### ISSUE TITLE
ERROR [internal] load metadata for docker.io/dev/api-base:latest

### ISSUE THREAD

**Issue by mishabachkur** [nevadskiy/laravel-nuxt-docker#44]
First of all, thank you for your work. 

I have encountered a problem. The screenshot shows the installation steps. @nevadskiy Could you please help me identify what the problem is?

You rock

Local machine:

MacBook Pro 2021
Apple M1 Pro
Ventura 13.0

Docker Desktop v4.17.0

![image](https://github.com/nevadskiy/laravel-nuxt-docker/assets/3975266/63c31fea-8ea0-4bc8-a0ef-92c1678f84f8)

**Comment by vavan19** [comment]
@mishabachkur Try authorising in a container registry
`docker login registry.example.com/mynamespace/myproject`

And then setting this registry in .env file

```
IMAGE_REGISTRY=registry.example.com/mynamespace/myproject
IMAGE_TAG=dev
```


https://docs.gitlab.com/ee/user/packages/container_registry/

And a video if it's not clear from the article
https://www.youtube.com/watch?v=ZJZGJTM23z0

Had this situation just now. Solved it and now sharing the answer.

**Comment by xalaida** [comment]
@mishabachkur sorry for late response. I have rewritten the Dockerfile using multi-stage builds, it should be fine now.
