### ISSUE TITLE
Add variable PROJECT_NAME

### ISSUE THREAD

**Issue by mishabachkur** [nevadskiy/laravel-nuxt-docker#46]
It would be convenient to have a variable PROJECT_NAME, for example, to be able to change the names of the network and containers. This is handy when using a template across multiple projects.

**Comment by xalaida** [comment]
@mishabachkur yes it is a good idea. for now I guess the easiest approach would be to just manually update the configuration according to your needs.

**Comment by mishabachkur** [comment]
Yes, currently it’s fastest to change manually, but in the future, it would be convenient to alter it simply through variable. Thank you

**Comment by xalaida** [comment]
Docker Compose accepts the `COMPOSE_PROJECT_NAME` environment variable

**Comment by xalaida** [comment]
Docker Compose accepts the `COMPOSE_PROJECT_NAME` environment variable
