### ISSUE TITLE
Package 'libbrotlienc', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by mcmc4519** [nevadskiy/laravel-nuxt-docker#47]
Hello from Ternopil, Ukraine :) 

Nice to meet you in case you visit my city.

Nice to see your project here, Vitalii. 

I have an issue.

I cloned you repo, than I send this commands:
`
cd ./api
./install.sh
`

I have faced an error: 

> 
> 9.509 checking for libbrotlienc... no
> 9.511 configure: error: Package requirements (libbrotlienc) were not met:
> 9.511 
> 9.511 Package 'libbrotlienc', required by 'virtual:world', not found
> 9.511 
> 9.511 Consider adjusting the PKG_CONFIG_PATH environment variable if you
> 9.511 installed software in a non-standard prefix.
> 9.511 
> 9.511 Alternatively, you may set the environment variables BROTLIENC_CFLAGS
> 9.511 and BROTLIENC_LIBS to avoid the need to call pkg-config.
> 9.511 See the pkg-config man page for more details.
> 9.537 ERROR: `/tmp/pear/temp/swoole/configure --with-php-config=/usr/local/bin/php-config --enable-sockets=no --enable-openssl=no --enable-mysqlnd=no --enable-swoole-curl=no --enable-cares=no --enable-brotli=yes --enable-swoole-pgsql=no --with-swoole-odbc=no --with-swoole-oracle=no --enable-swoole-sqlite=no' failed
> ------
> failed to solve: process "/bin/sh -c pecl install     swoole     redis     && docker-php-ext-install     pdo     pdo_pgsql     pcntl     opcache     && docker-php-ext-enable     swoole     redis     pcntl" did not complete successfully: exit code: 1
> 

**My envirement:** 

> Mac OS. Sequoia 15.0
> Apple M1 PRO
> docker latest version: 4.35.1

I have tried to run it on github codespace, it is the same problem

Would you please help me, Sir? :)

**Comment by xalaida** [comment]
Hi Ternopil :) 

PR is merged 

Thanks for the report
