### ISSUE TITLE
From Nginx to traefik

### ISSUE THREAD

**Issue by A-linea** [nevadskiy/laravel-nuxt-docker#6]
Greetings! 
Thanks for the build. I have a couple of questions:
Please tell me if there are plans to replace Nginx with Traefic. 
Can I use this build for production?

**Comment by xalaida** [comment]
You're welcome :)
Currently I use it only for development process.
What about Traefic I haven't even tried it yet, so for now I stick with Nginx.
The nearest plan is to add the production-ready build as a separate docker-compose.prod.yml configuration file but for now there is only development build here.

**Comment by A-linea** [comment]
Thank you for your response! It will be awesome to have a prod version, at this moment deploying the nuxt and Laravel API project, is a nutshell. Good luck!
