### ISSUE TITLE
Can't access http://localhost/api/storage/image.png

### ISSUE THREAD

**Issue by niqitos** [nevadskiy/laravel-nuxt-docker#8]
I have an image in `api/storage/app/public/image.png`. When I go to [localhost/api/storage/image.png](http://localhost/api/storage/image.png) I get Laravel 404. When I go to [localhost/storage/image.png](http://localhost/storage/image.png) I get nuxt empty page. [nginx:81/storage/image.png](http://nginx:81/storage/image.png) does not work as well. How do I access files in api storage from the front end?

**Comment by xalaida** [comment]
@niqitos Hi. You're right, there is an issue. It's unreachable now on the default 8080 port. 
I have used only nuxt `static` folder for simple static images. 
But if you want to access somehow storage images, make sure you ran `artisan storage:link` command, then go to [localhost:8081/storage/image.png](localhost:8081/storage/image.png) url. That should work.

**Comment by xalaida** [comment]
@niqitos 
The new v0.2 release supports the `/storage` urls.
